# This is a basic workflow to help you get started with Actions

name: deployment_to_server

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: 'Download artifact'
        uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: 'deploy website on server'
        env:
          ssh_host: ${{ secrets.SSH_HOST }}
          ssh_user: ${{ secrets.SSH_USER }}
          ssh_key: ${{ secrets.SSH_KEY }}
        run: |
          echo deploy to server
          eval $(ssh-agent -s)
          ssh-add <(echo "$ssh_key" | tr -d '\r')
          scp -o StrictHostKeyChecking=no -r index.html tutorial/ query/ cheatsheet/ assets/ $ssh_user@$ssh_host:/home/$ssh_user/nginx/html
          ssh -o StrictHostKeyChecking=no $ssh_user@$ssh_host "source /etc/profile && cd /home/$ssh_user/nginx/ && docker-compose down && docker-compose up -d"
        shell: bash
